//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWMS.SimpleDirectoryBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWMS.SimpleDirectoryBrowser.DefaultTemplates", typeof(DefaultTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;%Link%&quot;&gt;
        ///	&lt;li&gt;
        ///		&lt;table style=&quot;width: 100%&quot;&gt;
        ///			&lt;td style=&quot;width: 50%&quot;&gt;
        ///			%Name%
        ///			&lt;/td&gt;
        ///			&lt;td style=&quot;width: 22%&quot;&gt;
        ///			%Size%
        ///			&lt;/td&gt;
        ///			&lt;td style=&quot;width: 22%&quot;&gt;
        ///			%Date%
        ///			&lt;/td&gt;
        ///		&lt;/table&gt;
        ///	&lt;/li&gt;
        ///&lt;/a&gt;.
        /// </summary>
        internal static string DirectoryItemFileTemplate {
            get {
                return ResourceManager.GetString("DirectoryItemFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;%Link%&quot;&gt;
        ///	&lt;li&gt;
        ///		&lt;table style=&quot;width: 100%&quot;&gt;
        ///			&lt;td style=&quot;width: 45%&quot;&gt;
        ///			%Name%
        ///			&lt;/td&gt;
        ///			&lt;td style=&quot;width: 45%&quot;&gt;
        ///			%Date%
        ///			&lt;/td&gt;
        ///		&lt;/table&gt;
        ///	&lt;/li&gt;
        ///&lt;/a&gt;.
        /// </summary>
        internal static string DirectoryItemFolderTemplate {
            get {
                return ResourceManager.GetString("DirectoryItemFolderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=stylesheet href=&quot;https://creeperlv.github.io/Styles/cldesignv2/cldesignv2.css&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///    &lt;title&gt;Server Content Browser&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;div class=&quot;titleDiv&quot;&gt;
        ///            &lt;!--Title Div always on the top of the page--&gt;
        ///            &lt;p class=&quot;pageTitle&quot; style=&quot;text-align: center;&quot;&gt;Server Content Browser&lt;/p&gt;
        ///        &lt;/div&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DirectoryTemplate {
            get {
                return ResourceManager.GetString("DirectoryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=stylesheet href=&quot;https://creeperlv.github.io/Styles/cldesignv2/cldesignv2.css&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///    &lt;title&gt;Server Content Browser&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;div class=&quot;titleDiv&quot;&gt;
        ///            &lt;!--Title Div always on the top of the page--&gt;
        ///            &lt;p class=&quot;pageTitle&quot; style=&quot;text-align: center;&quot;&gt;Server Content Browser&lt;/p&gt;
        ///        &lt;/div&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextViewerTemplate {
            get {
                return ResourceManager.GetString("TextViewerTemplate", resourceCulture);
            }
        }
    }
}
